#!/bin/bash

# TODO: look at issue 11940 note for example of good summary of status

echo "Samples of disk fill"
awk '/^\// { print $1 " " $3 }' $1-df | sort | uniq -c

echo
for dev in $(head $1-df | awk '/^\// { print $1 }' | sort -u); do
   echo "Disk statistics for ${dev}"
   grep ${dev} $1-diskstats
done

echo
echo "InnoDB stats"
grep "Main thread" $1-innodb*
grep "queries inside" $1-innodb*
grep -i -A1 "pending" $1-innodb*

echo "InnoDB semaphores: threads are waiting at..."
awk '
   /has waited at/ { print $6 " " $7 " " $8 }
   ' $1-innodb* | sort | uniq -c | sort -rn
echo "InnoDB semaphores: threads are waiting on..."
awk '
   /^[XS]-lock on.*latch/ { print }
   ' $1-innodb* | sort | uniq -c | sort -rn
echo "InnoDB semaphores: each thread is blocking how many other threads?"
awk '
   /a [^ ]*er .thread id/ { print substr($5, 1, index($5, ")") - 1)}
   ' $1-innodb* | sort | uniq -c | sort -rn | awk '{printf "%18d blocks %3d others\n", $2, $1}'

exit

# TODO: do both in one pass with associative arrays
echo
echo "Source of connections to MySQL"
awk '/:3306/ { print substr($5, 0, index($5, ":") - 1) }' $1-netstat | sort | uniq -c | sort -rn
echo
echo "Status of connections to MySQL"
awk '/:3306/ { print $6 }' $1-netstat | sort | uniq -c | sort -rn

for i in 1 2; do
   echo
   echo "Users for processlist $i"
   awk -F: '/^ *User:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
   echo "States for processlist $i"
   awk -F: '/^ *State:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
   echo "Commands for processlist $i"
   awk -F: '/^ *Command:/{print $2}' $1-processlist$i | sort | uniq -c | sort -rn
done

echo
echo "Stacktraces"

awk '
   BEGIN { s = ""; }
   /Thread/ { print s; s = ""; }
   /^\#/ { if (s != "" ) { s = s "," $4} else { s = $4 } }
   END { print s }' \
   $1-stacktrace | sort | uniq -c | sort -rn

