#!/bin/bash
# This program is part of Aspersa (http://code.google.com/p/aspersa/)

# ########################################################################
# A script to watch MySQL and run the 'collect' program when some condition
# becomes true.  By default, it watches for a too-many-connections condition.
# This is a good script to run in a screen session.  It's separate from the
# 'collect' script because that lets you change 'collect' without stopping
# and restarting this one.
#
# The name 'stalk' is because 'watch' is already taken, and 'stalk' is fun.
#
# Author: Baron Schwartz
# ########################################################################

# ########################################################################
# Configuration settings.
# ########################################################################
# This is the max number of <whatever> we want to tolerate.  You can pass this
# in as the first command-line option if you want.
THRESHOLD=${1:-100}
# This is the interval between checks; pass it as the 2nd command-line option.
INTERVAL=${2:-30}
# This is the thing to check for.  You can pass this as the third option.
VARIABLE=${3:-Threads_connected}
# If the command you're running to detect the condition is allowed to return
# nothing (e.g. a grep line that might not even exist if there's no problem),
# then set this to "yes".
MAYBE_EMPTY="no"
# This is the location of the 'collect' script.
COLLECT="${HOME}/bin/collect";
# How long to sleep after collecting?
SLEEP=600

if [ "$(id -u)" != "0" ]; then
   echo 'Not running with root privileges!';
fi

while true; do
   date 

   # XXX This is where we decide whether to execute 'collect'.
   # XXX Customize this if needed.  The idea is to generate a number and store
   # XXX it into $detected, and if $detected > $THRESHOLD, then we'll execute
   # XXX the collection process.
   detected=$(mysqladmin ext | grep ${VARIABLE} | awk '{print $4}');
   execute="no"
   if [ -z "${detected}" -a ${MAYBE_EMPTY} = "no" ]; then
      execute="yes" # Oops, couldn't connect, maybe max_connections problem.
      echo "The detected value is empty; something failed?  Exit status is $?"
   elif [ "${detected:-0}" -gt ${THRESHOLD} ]; then
      execute="yes"
   fi

   # XXX Stop customizing here; everything above should be what you need.
   if [ "${execute:-no}" = "yes" ]; then 
      echo "Executing collection script; ${VARIABLE} = ${detected}"
      ${COLLECT}
      echo "sleeping ${SLEEP} seconds to avoid DOS attack"
      sleep ${SLEEP}
   else
      sleep ${INTERVAL}
   fi
done
