#!/bin/bash
#parse_free_minus_b /tmp/aspersa

cat <<EOF > $1
       Total | 3.89G
        Free | 1.42G
        Used | physical = 2.47G, swap = 0.00k, virtual = 2.47G
     Buffers | 131.84M
      Caches | 1.92G
       Dirty | 60 kB
EOF

cat <<EOF > $2
             total       used       free     shared    buffers     cached
Mem:    67565047808 67378626560  186421248          0  540524544 14223519744
-/+ buffers/cache: 52614582272 14950465536
Swap:   34356985856     258048 34356727808
MemTotal:     65981492 kB
MemFree:        182044 kB
Buffers:        527856 kB
Cached:       13890156 kB
SwapCached:          0 kB
Active:       56324996 kB
Inactive:      8533644 kB
HighTotal:           0 kB
HighFree:            0 kB
LowTotal:     65981492 kB
LowFree:        182044 kB
SwapTotal:    33551744 kB
SwapFree:     33551492 kB
Dirty:         2956324 kB
Writeback:           0 kB
AnonPages:    50440412 kB
Mapped:          35656 kB
Slab:           785288 kB
PageTables:     104892 kB
NFS_Unstable:        0 kB
Bounce:              0 kB
CommitLimit:  66542488 kB
Committed_AS: 51553668 kB
VmallocTotal: 34359738367 kB
VmallocUsed:    279488 kB
VmallocChunk: 34359458839 kB
HugePages_Total:     0
HugePages_Free:      0
HugePages_Rsvd:      0
Hugepagesize:     2048 kB
EOF
