#!/bin/bash

# All variables are named GL_whatever so they don't get overwritten with stuff
# that happens in the functions sourced.
GL_input="/tmp/aspersa"
GL_reference="/tmp/aspersa-reference"
GL_result="/tmp/aspersa-result"

if [ "$*" ]; then
   forloop="$*"
else
   forloop="$(ls | grep auto | cut -d- -f3-)"
fi

for dir in $forloop; do
   . ../$dir
   # Runs all test files.  The format of the test file is as follows:
   # - line 1 is the shebang
   # - line 2 is the command to run, commented out
   # - argument 1 is the file to which the reference result should be printed
   # - argument 2 is the file to which the input should be printed
   
   for GL_file in `ls auto-tests-$dir | ./sort_random `; do
      GL_file="auto-tests-$dir/${GL_file}"
   
      # Get the command to run
      GL_cmd="$(head -n2 $GL_file | tail -n1 | cut -b2-)"
   
      # Execute the file and tell it where to save the input & reference result
      if [ -x "${GL_file}" ]; then
         $GL_file "${GL_reference}" "${GL_input}"
      else
         echo "NOK ${GL_file} (not executable)"
         continue
      fi
   
      # Execute the command
      before=$(date +%s.%N)
      ${GL_cmd} > "${GL_result}"
      after=$(date +%s.%N)
      diff="$(echo $before $after | awk '{printf "%8.3f", $2-$1}')"
   
      # Is the result the same as the reference result?
      if diff -q "${GL_result}" "${GL_reference}" >/dev/null; then
         echo " OK $diff $GL_cmd $GL_file"
      else
         echo "NOK $diff $GL_cmd $GL_file"
         # Indent and display the first 10 lines
         diff "${GL_result}" "${GL_reference}" | sed -e 's/^/    /' -e '10q'
      fi
   
      # Clean up
      rm -f /tmp/aspersa*
   done
   
   echo "#### DONE ####"
done
