#!/bin/bash
#group_by_sample samples/diskstats-001.txt

cat <<EOF > $1
  #ts device          rd_s rd_avkb rd_mb_s rd_mrg rd_cnc   rd_rt    wr_s wr_avkb wr_mb_s wr_mrg wr_cnc   wr_rt busy in_prg
  2.0 <8>            466.5    22.3    10.2     0%    1.4    23.9  1184.0    21.3    24.6    18%    0.0     0.2  12%     18
  4.0 <8>            373.0    23.6     8.6     0%    1.3    27.4   592.0    22.8    13.2    16%    0.0     0.1  11%     17
  6.0 <8>            424.0    21.3     8.8     0%    1.4    25.5   993.5    24.9    24.1     3%    0.0     0.1  11%      9
  7.0 <8>            680.0    18.3    12.1     0%    2.0    23.8  2299.0    21.7    48.7    23%    0.1     0.2  22%      5
EOF

cp samples/diskstats-001.txt /tmp/aspersa
