#!/bin/bash
#group_by_disk samples/diskstats-001.txt

cat <<EOF > $1
  #ts device          rd_s rd_avkb rd_mb_s rd_mrg rd_cnc   rd_rt    wr_s wr_avkb wr_mb_s wr_mrg wr_cnc   wr_rt busy in_prg
  {4} ram0             0.0     0.0     0.0     0%    0.0     0.0     0.0     0.0     0.0     0%    0.0     0.0   0%      0
  {4} cciss/c0d0       0.0     0.0     0.0     0%    0.0     0.0    17.7    28.1     0.5    86%    0.0     0.6   0%      0
  {4} cciss/c0d0p1     0.0     0.0     0.0     0%    0.0     0.0     0.0     0.0     0.0     0%    0.0     0.0   0%      0
  {4} cciss/c0d0p2     0.0     0.0     0.0     0%    0.0     0.0    17.7    28.1     0.5    86%    0.0     0.6   0%      0
  {4} cciss/c0d1     458.1    21.5     9.6     0%    1.4    25.1   985.0    24.2    23.3     0%    0.0     0.1  13%     13
  {4} cciss/c1d0       0.0     0.0     0.0     0%    0.0     0.0     0.0     0.0     0.0     0%    0.0     0.0   0%      0
  {4} dm-0             0.0     0.0     0.0     0%    0.0     0.0    99.3     4.0     0.4     0%    0.0     0.7   0%      0
  {4} md0              0.0     0.0     0.0     0%    0.0     0.0     0.0     0.0     0.0     0%    0.0     0.0   0%      0
EOF

cp samples/diskstats-001.txt /tmp/aspersa
